wandb_version: 1

activation:
  value: silu
batch_norm:
  value: false
batch_size:
  value: 128
data_augmentation:
  value: false
dense_neurons:
  value: 512
dropout_rate:
  value: 0.3
epochs:
  value: 10
filter_organization:
  value: double
filter_size:
  value: 5
learning_rate:
  value: 0.0001
num_filters:
  value: 32
