wandb_version: 1

activation:
  value: mish
batch_norm:
  value: true
batch_size:
  value: 32
data_augmentation:
  value: true
dense_neurons:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 10
filter_organization:
  value: half
filter_size:
  value: 3
learning_rate:
  value: 0.001
num_filters:
  value: 128
