wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 32
data_augmentation:
  value: false
dense_neurons:
  value: 512
dropout_rate:
  value: 0.45291084888777033
epochs:
  value: 10
filter_organization:
  value: half
filter_size:
  value: 3
learning_rate:
  value: 0.0020716825647332437
num_filters:
  value: 128
