_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
activation:
    value: relu
batch_norm:
    value: true
batch_size:
    value: 64
data_augmentation:
    value: false
dense_neurons:
    value: 256
dropout_rate:
    value: 0.38828655992877104
epochs:
    value: 10
filter_organization:
    value: double
filter_size:
    value: 5
learning_rate:
    value: 0.006826835053332589
num_filters:
    value: 32
