_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
activation:
    value: gelu
batch_norm:
    value: false
batch_size:
    value: 32
data_augmentation:
    value: true
data_dir:
    value: inaturalist_12K
dense_neurons:
    value: 512
dropout_rate:
    value: 0.3406873835839702
epochs:
    value: 15
filter_organization:
    value: same
filter_size:
    value: 3
learning_rate:
    value: 0.0016724005876545866
num_filters:
    value: 32
num_workers:
    value: 4
wandb_project:
    value: CNN-From-Scratch-Assignment
wandb_run_id:
    value: d274sfof
