_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
activation:
    value: relu
batch_norm:
    value: true
batch_size:
    value: 32
data_augmentation:
    value: false
data_dir:
    value: inaturalist_12K
dense_neurons:
    value: 512
dropout_rate:
    value: 0.49855221748546985
epochs:
    value: 10
filter_organization:
    value: half
filter_size:
    value: 5
img_size:
    value: 224
learning_rate:
    value: 0.005421664048434102
num_filters:
    value: 64
num_workers:
    value: 4
seed:
    value: 42
val_split:
    value: 0.2
wandb_project:
    value: CNN_FROM_SCRATCH_SWEEP
wandb_run_id:
    value: u01ahttl
