wandb_version: 1

activation:
  value: gelu
batch_norm:
  value: true
batch_size:
  value: 64
data_augmentation:
  value: false
dense_neurons:
  value: 512
dropout_rate:
  value: 0.49543242755412786
epochs:
  value: 10
filter_organization:
  value: double
filter_size:
  value: 3
learning_rate:
  value: 0.001007000527681697
num_filters:
  value: 128
