wandb_version: 1

activation:
  value: mish
batch_norm:
  value: false
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 128
dropout_rate:
  value: 0.17643730010086656
epochs:
  value: 10
filter_organization:
  value: half
filter_size:
  value: 3
learning_rate:
  value: 0.0010487932829924694
num_filters:
  value: 64
