wandb_version: 1

activation:
  value: mish
batch_norm:
  value: false
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 128
dropout_rate:
  value: 0.26591975945569324
epochs:
  value: 15
filter_organization:
  value: double
filter_size:
  value: 5
learning_rate:
  value: 0.00011238160093271698
num_filters:
  value: 64
