wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 64
data_augmentation:
  value: false
dense_neurons:
  value: 256
dropout_rate:
  value: 0.26409573372797107
epochs:
  value: 15
filter_organization:
  value: half
filter_size:
  value: 5
learning_rate:
  value: 0.007210800195757017
num_filters:
  value: 128
