wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 32
data_augmentation:
  value: false
dense_neurons:
  value: 128
dropout_rate:
  value: 0.15906846330245986
epochs:
  value: 15
filter_organization:
  value: double
filter_size:
  value: 5
learning_rate:
  value: 0.0008685020288531751
num_filters:
  value: 64
