wandb_version: 1

activation:
  value: relu
batch_norm:
  value: true
batch_size:
  value: 32
data_augmentation:
  value: true
dense_neurons:
  value: 128
dropout_rate:
  value: 0.2280956118639181
epochs:
  value: 15
filter_organization:
  value: double
filter_size:
  value: 3
learning_rate:
  value: 0.00029505890496402896
num_filters:
  value: 64
