wandb_version: 1

activation:
  value: gelu
batch_norm:
  value: false
batch_size:
  value: 64
data_augmentation:
  value: false
dense_neurons:
  value: 512
dropout_rate:
  value: 0.4560390181159063
epochs:
  value: 15
filter_organization:
  value: same
filter_size:
  value: 5
learning_rate:
  value: 0.008224505400979685
num_filters:
  value: 64
