wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 512
dropout_rate:
  value: 0.3935666984006415
epochs:
  value: 15
filter_organization:
  value: half
filter_size:
  value: 3
learning_rate:
  value: 0.00041761360482927147
num_filters:
  value: 128
