wandb_version: 1

activation:
  value: silu
batch_norm:
  value: false
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 256
dropout_rate:
  value: 0.18059070121434587
epochs:
  value: 15
filter_organization:
  value: half
filter_size:
  value: 3
learning_rate:
  value: 0.0037675843923687543
num_filters:
  value: 64
