wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 32
data_augmentation:
  value: true
dense_neurons:
  value: 512
dropout_rate:
  value: 0.2636262151518316
epochs:
  value: 15
filter_organization:
  value: half
filter_size:
  value: 5
learning_rate:
  value: 0.00040168636574394647
num_filters:
  value: 32
