wandb_version: 1

activation:
  value: mish
batch_norm:
  value: true
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 512
dropout_rate:
  value: 0.19679648194830257
epochs:
  value: 15
filter_organization:
  value: same
filter_size:
  value: 3
learning_rate:
  value: 0.00038935700874212893
num_filters:
  value: 64
