wandb_version: 1

activation:
  value: gelu
batch_norm:
  value: false
batch_size:
  value: 64
data_augmentation:
  value: false
dense_neurons:
  value: 256
dropout_rate:
  value: 0.21639806527255012
epochs:
  value: 15
filter_organization:
  value: double
filter_size:
  value: 3
learning_rate:
  value: 0.0008109003088153696
num_filters:
  value: 128
