wandb_version: 1

activation:
  value: mish
batch_norm:
  value: true
batch_size:
  value: 128
data_augmentation:
  value: false
dense_neurons:
  value: 256
dropout_rate:
  value: 0.2
epochs:
  value: 10
filter_organization:
  value: same
filter_size:
  value: 3
learning_rate:
  value: 0.001
num_filters:
  value: 32
