wandb_version: 1

activation:
  value: silu
batch_norm:
  value: false
batch_size:
  value: 32
data_augmentation:
  value: false
dense_neurons:
  value: 512
dropout_rate:
  value: 0.5
epochs:
  value: 10
filter_organization:
  value: half
filter_size:
  value: 7
learning_rate:
  value: 0.0001
num_filters:
  value: 32
