wandb_version: 1

activation:
  value: gelu
batch_norm:
  value: true
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 128
dropout_rate:
  value: 0.1555158702218946
epochs:
  value: 10
filter_organization:
  value: same
filter_size:
  value: 5
learning_rate:
  value: 0.0031051932238553587
num_filters:
  value: 128
