wandb_version: 1

activation:
  value: gelu
batch_norm:
  value: true
batch_size:
  value: 32
data_augmentation:
  value: true
dense_neurons:
  value: 128
dropout_rate:
  value: 0.44058915942084886
epochs:
  value: 10
filter_organization:
  value: double
filter_size:
  value: 5
learning_rate:
  value: 0.008743369700458928
num_filters:
  value: 64
