wandb_version: 1

activation:
  value: relu
batch_norm:
  value: true
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 512
dropout_rate:
  value: 0.38329499964376745
epochs:
  value: 10
filter_organization:
  value: double
filter_size:
  value: 5
learning_rate:
  value: 0.0025823286748450232
num_filters:
  value: 32
