wandb_version: 1

activation:
  value: relu
batch_norm:
  value: false
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 25
dropout_rate:
  value: 0.5
epochs:
  value: 10
filter_organization:
  value: double
filter_size:
  value: 5
learning_rate:
  value: 0.0001
num_filters:
  value: 128
