wandb_version: 1

activation:
  value: mish
batch_norm:
  value: false
batch_size:
  value: 32
data_augmentation:
  value: false
dense_neurons:
  value: 128
dropout_rate:
  value: 0.3475880784680211
epochs:
  value: 10
filter_organization:
  value: double
filter_size:
  value: 3
learning_rate:
  value: 0.00014551381052426015
num_filters:
  value: 128
