wandb_version: 1

activation:
  value: mish
batch_norm:
  value: true
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 128
dropout_rate:
  value: 0.21576829710721093
epochs:
  value: 10
filter_organization:
  value: half
filter_size:
  value: 5
learning_rate:
  value: 0.00014100792103384488
num_filters:
  value: 128
