_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.9
            "13": windows-amd64
activation:
    value: mish
batch_norm:
    value: true
batch_size:
    value: 32
data_augmentation:
    value: true
data_dir:
    value: inaturalist_12K
dense_neurons:
    value: 128
dropout_rate:
    value: 0.3
epochs:
    value: 10
filter_organization:
    value: half
filter_size:
    value: 3
learning_rate:
    value: 0.001
num_filters:
    value: 128
