wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 128
data_augmentation:
  value: true
dense_neurons:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 10
filter_organization:
  value: double
filter_size:
  value: 3
learning_rate:
  value: 0.0001
num_filters:
  value: 128
