wandb_version: 1

activation:
  value: mish
batch_norm:
  value: false
batch_size:
  value: 64
data_augmentation:
  value: false
dense_neurons:
  value: 256
dropout_rate:
  value: 0.24549151256913168
epochs:
  value: 10
filter_organization:
  value: same
filter_size:
  value: 3
learning_rate:
  value: 0.006825143938054854
num_filters:
  value: 32
