wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 32
data_augmentation:
  value: true
dense_neurons:
  value: 256
dropout_rate:
  value: 0.32344843564412984
epochs:
  value: 10
filter_organization:
  value: half
filter_size:
  value: 3
learning_rate:
  value: 0.003931653624884796
num_filters:
  value: 64
