wandb_version: 1

activation:
  value: mish
batch_norm:
  value: true
batch_size:
  value: 64
data_augmentation:
  value: false
dense_neurons:
  value: 512
dropout_rate:
  value: 0.3737240074610531
epochs:
  value: 10
filter_organization:
  value: double
filter_size:
  value: 5
learning_rate:
  value: 0.002627405510644801
num_filters:
  value: 64
