wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 32
data_augmentation:
  value: true
dense_neurons:
  value: 512
dropout_rate:
  value: 0.39319158362798634
epochs:
  value: 10
filter_organization:
  value: same
filter_size:
  value: 3
learning_rate:
  value: 0.0010595375067730874
num_filters:
  value: 32
