wandb_version: 1

activation:
  value: relu
batch_norm:
  value: false
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 256
dropout_rate:
  value: 0.14646301950894092
epochs:
  value: 10
filter_organization:
  value: same
filter_size:
  value: 5
learning_rate:
  value: 0.003432652494081283
num_filters:
  value: 64
