wandb_version: 1

activation:
  value: mish
batch_norm:
  value: true
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 128
dropout_rate:
  value: 0.4095325341549958
epochs:
  value: 10
filter_organization:
  value: half
filter_size:
  value: 5
learning_rate:
  value: 0.00010902157500893571
num_filters:
  value: 32
