wandb_version: 1

activation:
  value: gelu
batch_norm:
  value: false
batch_size:
  value: 32
data_augmentation:
  value: true
dense_neurons:
  value: 256
dropout_rate:
  value: 0.2
epochs:
  value: 10
filter_organization:
  value: same
filter_size:
  value: 5
learning_rate:
  value: 0.001
num_filters:
  value: 32
