wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 64
data_augmentation:
  value: true
dense_neurons:
  value: 256
dropout_rate:
  value: 0.330672270662158
epochs:
  value: 10
filter_organization:
  value: half
filter_size:
  value: 5
learning_rate:
  value: 0.001458671611174068
num_filters:
  value: 32
