wandb_version: 1

activation:
  value: relu
batch_norm:
  value: true
batch_size:
  value: 32
data_augmentation:
  value: true
dense_neurons:
  value: 512
dropout_rate:
  value: 0.35042557341581937
epochs:
  value: 10
filter_organization:
  value: same
filter_size:
  value: 5
learning_rate:
  value: 0.0028534551167354247
num_filters:
  value: 64
